server:
  port: 8082

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jeffyxu/rconfig.git
          username: kaixumvp@163.com
          password: xukai19921224?

eureka:
  instance:
    hostname: 39.99.191.129
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://xukai:123456@${eureka.instance.hostname}:8081/eureka


management:
  endpoints:
    web:
      exposure:
        include: '*'
